# ====================本服务配置====================
server: 
  ip: localhost
  port: 9753
  
spring:
  application:
    name: obt-file-local
  servlet: 
    multipart: 
      maxFileSize: 100MB
      maxRequestSize: 100MB

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: obt_zq_exam_321
    url: jdbc:mysql://10.8.6.129:3106/obtdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true

fdfs:
#  trackerList: 47.115.94.67:22122    # tracker地址，多个可fdfs.trackerList[0]、fdfs.trackerList[1]等方式配置
  trackerList: 
    - 10.8.6.127:22122
    - 10.8.6.128:22122
  connect-timeout: 5000    # 连接超时时间
  so-timeout: 6000    # 读取inputsream阻塞时间
  pool:
    max-total: 200    # 连接池最大数量 
    max-total-per-key: 20    # 每个tracker地址的最大连接数
    max-wait-millis: 25000    # 连接耗尽时等待获取连接的最大毫秒数
  thumbImage:     # 缩略图相关配置
    height: 150
    width: 150

# ====================management====================
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      showDetails: ALWAYS

# =======================basis.druid======================
basis.druid:
  # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
  initialSize: 1
  # 最小连接池数量
  minIdle: 1
  # 最大连接池数量
  maxActive: 10
  # 配置获取连接等待超时的时间
  maxWait: 10000
  #  配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  #  配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  #  验证连接有效与否的SQL，不同的数据配置不同
  validationQuery: select 1
  #  建议配置为true，不影响性能，并且保证安全性。
  #  申请连接的时候检测，如果空闲时间大于
  #  timeBetweenEvictionRunsMillis，
  #  执行validationQuery检测连接是否有效。
  testWhileIdle: true
  #  申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
  #  这里建议配置为TRUE，防止取到的连接不可用
  testOnBorrow: true
  #  归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
  testOnReturn: false
  #  是否缓存preparedStatement，也就是PSCache。
  #  PSCache对支持游标的数据库性能提升巨大，比如说oracle。
  #  在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
  #  作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录，
  #  该应该是支持PSCache。
  #  打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  #  属性类型是字符串，通过别名的方式配置扩展插件，
  #  常用的插件有：
  #  监控统计用的filter:stat
  #  日志用的filter:log4j
  #  防御sql注入的filter:wall
  filters: stat
  # 访问的用户名
  loginUsername: hyt
  # 访问的密码
  loginPassword: hyt


# ====================MybatisPlus====================
mybatis-plus:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# ====================上传图片和视频参数配置====================
monitor:
  fastDfs:
    httpUrl: http://10.8.6.127:8888/
  face:
    appId: B2Sr7AXQBPvocFZpXjpc9JZeNCAWhTmNaQS3D5Uc2Xah
    sdkKey: 87bCLUjsqo4rpZfGh5RZVmMbyyZWyG7mi7u7hPPoqqku
    activeKey: 82Y1-113C-313R-H569
    #activeKey: 82Y1-113C-312T-MJQC
    faceQuality: 0.25
    faceSimilarScore: 0.7